//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSigma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGMAEntities : DbContext
    {
        public SIGMAEntities()
            : base("name=SIGMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ViewModels.VisitorViewModel>().ToTable("Visitor");
        }


        public virtual DbSet<Visitor> Visitor { get; set; }

        public System.Data.Entity.DbSet<WebSigma.Models.ViewModels.VisitorViewModel> VisitorViewModels { get; set; }
    }
}
